plugins { id 'com.android.application' }

android {
    namespace 'com.example.nativetemplate'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.nativetemplate'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'

        ndk { abiFilters 'armeabi-v7a' }
        externalNativeBuild { cmake { cppFlags '-std=c++17' } }
    }

    externalNativeBuild {
        cmake { path file('src/main/cpp/CMakeLists.txt'); version '3.22.1' }
    }
}
